### ISSUE TITLE
Returns 0s for partition files. 

### ISSUE THREAD

**Issue by slvrshot** [btmartin721/extractVariantSites4raxml#3]
Hello I have some WGS samples and I ran gubbins following whole genome SNP alignment to remove recombinant sites which produces a phylip file. I used that as input and ran your script as stated in the readme `python3 ./ascbias.py -p Gubbins.filtered_polymorphic_sites.phylip -o testout.phy`

The output file just returns 0s....specifically 0 0 0 0. 

Any clue and why that might be?

**Comment by btmartin721** [comment]
Sorry for the potential bug. I'm not sure off the top of my head why it might be doing that. I'd need to test it with your phylip input file. If you want, you can send it to me privately btm002@uark.edu, or you can upload it here.

-Bradley

**Comment by slvrshot** [comment]
> Sorry for the potential bug. I'm not sure off the top of my head why it might be doing that. I'd need to test it with your phylip input file. If you want, you can send it to me privately [btm002@uark.edu](mailto:btm002@uark.edu), or you can upload it here.
> 
> -Bradley

I sent that email! Thanks again!

**Comment by slvrshot** [comment]
I think you can close this. I fed the script the output with gaps and it correctly counted the invariant sites. Thank you. This is a life saver.

**Comment by btmartin721** [comment]
Ok thanks for letting me know. Glad it helped. Also, I apologize for my delay in getting to this issue, but I'm glad it was resolved.
