### ISSUE TITLE
Counting and extracting invariant sites question.

### ISSUE THREAD

**Issue by slvrshot** [btmartin721/extractVariantSites4raxml#4]
Hi again - Well I think your script runs fine but I noticed that there might be one small issue that could potentially inflate counts of the invariant sites. In fact I've tested this with another in-house script (its not quite as fast and I did not write it). Lets assume in Col 1 or any col for that matter there is one or 2 samples with an N at one position and every other genome contain bases at that position. Will your script call this position as a monomorphic site? Because my understanding is even if there are bases at all the other positions, that site is not considered monomorphic. 

Based on your example...will this:

ANAT  
AART  
AAAG  
AA-G  

Produce this?

AT  
AT  
AG  
AG  

Thanks

**Comment by btmartin721** [comment]
RaxML considers those invariant sites because the N could be an A, T, G, or C. My script should remove those two sites, which is what it needs to do because RaxML will crash otherwise. It's not the normal definition of monomorphic sites but that's how RaxML handles them.

**Comment by slvrshot** [comment]
I'm trying to think what else could be causing the inflated counts because their sum (sum of A/C/G/Ts) is basically the number of sites of the entire bacterial genome: roughly 2.2M. If all the sites are invariant that would imply the isolates are clonal which they are not.

**Comment by btmartin721** [comment]
It could be gaps. I'm not sure on that but if you want I can take a look this weekend. I seem to remember that this script might not be perfect in all datasets, and i think maybe gaps throw it off. I'm normally very thorough with my coding and testing practices but this was one of my early scripts when I was learning python and I've noticed it sometimes has issues. I also wrote this as a quick and dirty script for a specific need that I had.

 If it's the same dataset you sent me the other day I'll go ahead and look at it. I'm currently not super speedy about getting to this stuff lately because I have a newborn baby at home but I'll try to work on it this weekend.

**Comment by slvrshot** [comment]
> It could be gaps. I'm not sure on that but if you want I can take a look this weekend. I seem to remember that this script might not be perfect in all datasets, and i think maybe gaps throw it off. I'm normally very thorough with my coding and testing practices but this was one of my early scripts when I was learning python and I've noticed it sometimes has issues. I also wrote this as a quick and dirty script for a specific need that I had.
> 
> If it's the same dataset you sent me the other day I'll go ahead and look at it. I'm currently not super speedy about getting to this stuff lately because I have a newborn baby at home but I'll try to work on it this weekend.

Congrats on the baby! I totally understand. I can already tell you that the whole genome SNP alignment was generated in snippy and there are gaps and Ns. I'm awful with python so kudos to you. I might need to send you a dropbox link though to another file. I'll probably send that later tonight. Thanks!

**Comment by slvrshot** [comment]
Okay I am closing this for real now. You have been a big help. After thinking about this more...I found the solution. I used `snp-sites -cbp outputprefix input.phylip` option to extract the monomorphic sites ACGT only and export in a phylip file. Then I used the phylip file as input into your script. The results are the exact same as the internal script. So everything is fine. Enjoy time with the new baby. You can ignore the .aln file I sent. Take care!
